<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Gnanadeep Settykara" />

<meta name="date" content="2024-02-26" />

<title>Bellabeat Case Study</title>

<script src="Bellabeat_Case_Study_files/header-attrs-2.25/header-attrs.js"></script>
<script src="Bellabeat_Case_Study_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Bellabeat_Case_Study_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="Bellabeat_Case_Study_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Bellabeat_Case_Study_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Bellabeat_Case_Study_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="Bellabeat_Case_Study_files/navigation-1.1/tabsets.js"></script>
<link href="Bellabeat_Case_Study_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Bellabeat_Case_Study_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">Bellabeat Case Study</h1>
<h4 class="author">Gnanadeep Settykara</h4>
<h4 class="date">2024-02-26</h4>

</div>


<div id="ask" class="section level3">
<h3><strong>Ask</strong></h3>
<div id="business-task" class="section level4">
<h4><strong>Business Task</strong></h4>
<p>Bellabeat, a high-tech company focusing on health-centric smart
products, wants to leverage smart device usage data to gain insights
into consumer behavior. The goal is to understand trends in smart device
usage, explore their potential application to Bellabeat customers, and
use these insights to inform the company’s marketing strategy.</p>
</div>
<div id="key-stakeholders" class="section level4">
<h4><strong>Key Stakeholders</strong></h4>
<ul>
<li>Urška Sršen (Co-founder)</li>
<li>Sando Mur (Co-founder)</li>
<li>Bellabeat Marketing Department</li>
</ul>
</div>
<div id="objectives" class="section level4">
<h4><strong>Objectives</strong></h4>
<ul>
<li>Analyze trends in non-Bellabeat smart device usage.</li>
<li>Understand how these trends may relate to Bellabeat’s target
customers.</li>
<li>Formulate high-level recommendations for Bellabeat’s marketing
strategy based on the smart device usage analysis.</li>
</ul>
</div>
</div>
<div id="prepare" class="section level3">
<h3><strong>Prepare</strong></h3>
<p>Data Source: <a
href="https://www.kaggle.com/datasets/arashnic/fitbit"
class="uri">https://www.kaggle.com/datasets/arashnic/fitbit</a></p>
<p>Data follows <strong>ROCCC</strong> approach:</p>
<ul>
<li><p><strong>Reliable</strong>: The data seems reliable as it comes
from FitBit users who voluntarily submitted their personal tracker data.
FitBit is a well-known brand for fitness tracking, and users typically
provide accurate information.</p></li>
<li><p><strong>Original</strong>: The data source is mentioned as public
data collected directly from FitBit users via a survey on Amazon
Mechanical Turk. This suggests that the data is original and not a
secondary source.</p></li>
<li><p><strong>Current</strong>: The information doesn’t explicitly
mention the timeframe of the data, so it’s unclear if the data is
current. Knowing the date range or the period of data collection would
help assess its currency.</p></li>
<li><p><strong>Comprehensive</strong>: The data appears to cover
minute-level output for physical activity, heart rate, and sleep
monitoring. This suggests a comprehensive dataset, especially if it
includes a diverse set of users.</p></li>
<li><p><strong>Cited</strong>: The data license is mentioned as CC0:
Public Domain.</p></li>
</ul>
<pre class="r"><code># Loading packages
library(tidyverse)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)</code></pre>
<p>Loading and Exploring the data</p>
<pre class="r"><code># Importing Datasets
activity_data &lt;- read.csv(&quot;C:/Users/Deep/Desktop/SE/Case study Data Analytics/Dataset/fitbit/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv&quot;)
calories_data &lt;- read.csv(&quot;C:/Users/Deep/Desktop/SE/Case study Data Analytics/Dataset/fitbit/Fitabase Data 4.12.16-5.12.16/dailyCalories_merged.csv&quot;)
intensities_data &lt;- read.csv(&quot;C:/Users/Deep/Desktop/SE/Case study Data Analytics/Dataset/fitbit/Fitabase Data 4.12.16-5.12.16/dailyIntensities_merged.csv&quot;)
steps_data &lt;- read.csv(&quot;C:/Users/Deep/Desktop/SE/Case study Data Analytics/Dataset/fitbit/Fitabase Data 4.12.16-5.12.16/dailySteps_merged.csv&quot;)
sleep_data &lt;- read.csv(&quot;C:/Users/Deep/Desktop/SE/Case study Data Analytics/Dataset/fitbit/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv&quot;)
weight_data &lt;- read.csv(&quot;C:/Users/Deep/Desktop/SE/Case study Data Analytics/Dataset/fitbit/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv&quot;)

# Explore the data
head(activity_data)</code></pre>
<pre><code>##           Id ActivityDate TotalSteps TotalDistance TrackerDistance
## 1 1503960366    4/12/2016      13162          8.50            8.50
## 2 1503960366    4/13/2016      10735          6.97            6.97
## 3 1503960366    4/14/2016      10460          6.74            6.74
## 4 1503960366    4/15/2016       9762          6.28            6.28
## 5 1503960366    4/16/2016      12669          8.16            8.16
## 6 1503960366    4/17/2016       9705          6.48            6.48
##   LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
## 1                        0               1.88                     0.55
## 2                        0               1.57                     0.69
## 3                        0               2.44                     0.40
## 4                        0               2.14                     1.26
## 5                        0               2.71                     0.41
## 6                        0               3.19                     0.78
##   LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
## 1                6.06                       0                25
## 2                4.71                       0                21
## 3                3.91                       0                30
## 4                2.83                       0                29
## 5                5.04                       0                36
## 6                2.51                       0                38
##   FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
## 1                  13                  328              728     1985
## 2                  19                  217              776     1797
## 3                  11                  181             1218     1776
## 4                  34                  209              726     1745
## 5                  10                  221              773     1863
## 6                  20                  164              539     1728</code></pre>
<pre class="r"><code>head(intensities_data)</code></pre>
<pre><code>##           Id ActivityDay SedentaryMinutes LightlyActiveMinutes
## 1 1503960366   4/12/2016              728                  328
## 2 1503960366   4/13/2016              776                  217
## 3 1503960366   4/14/2016             1218                  181
## 4 1503960366   4/15/2016              726                  209
## 5 1503960366   4/16/2016              773                  221
## 6 1503960366   4/17/2016              539                  164
##   FairlyActiveMinutes VeryActiveMinutes SedentaryActiveDistance
## 1                  13                25                       0
## 2                  19                21                       0
## 3                  11                30                       0
## 4                  34                29                       0
## 5                  10                36                       0
## 6                  20                38                       0
##   LightActiveDistance ModeratelyActiveDistance VeryActiveDistance
## 1                6.06                     0.55               1.88
## 2                4.71                     0.69               1.57
## 3                3.91                     0.40               2.44
## 4                2.83                     1.26               2.14
## 5                5.04                     0.41               2.71
## 6                2.51                     0.78               3.19</code></pre>
<pre class="r"><code>head(calories_data)</code></pre>
<pre><code>##           Id ActivityDay Calories
## 1 1503960366   4/12/2016     1985
## 2 1503960366   4/13/2016     1797
## 3 1503960366   4/14/2016     1776
## 4 1503960366   4/15/2016     1745
## 5 1503960366   4/16/2016     1863
## 6 1503960366   4/17/2016     1728</code></pre>
<pre class="r"><code>head(steps_data)</code></pre>
<pre><code>##           Id ActivityDay StepTotal
## 1 1503960366   4/12/2016     13162
## 2 1503960366   4/13/2016     10735
## 3 1503960366   4/14/2016     10460
## 4 1503960366   4/15/2016      9762
## 5 1503960366   4/16/2016     12669
## 6 1503960366   4/17/2016      9705</code></pre>
<pre class="r"><code>head(sleep_data)</code></pre>
<pre><code>##           Id              SleepDay TotalSleepRecords TotalMinutesAsleep
## 1 1503960366 4/12/2016 12:00:00 AM                 1                327
## 2 1503960366 4/13/2016 12:00:00 AM                 2                384
## 3 1503960366 4/15/2016 12:00:00 AM                 1                412
## 4 1503960366 4/16/2016 12:00:00 AM                 2                340
## 5 1503960366 4/17/2016 12:00:00 AM                 1                700
## 6 1503960366 4/19/2016 12:00:00 AM                 1                304
##   TotalTimeInBed
## 1            346
## 2            407
## 3            442
## 4            367
## 5            712
## 6            320</code></pre>
<pre class="r"><code>head(weight_data)</code></pre>
<pre><code>##           Id                  Date WeightKg WeightPounds Fat   BMI
## 1 1503960366  5/2/2016 11:59:59 PM     52.6     115.9631  22 22.65
## 2 1503960366  5/3/2016 11:59:59 PM     52.6     115.9631  NA 22.65
## 3 1927972279  4/13/2016 1:08:52 AM    133.5     294.3171  NA 47.54
## 4 2873212765 4/21/2016 11:59:59 PM     56.7     125.0021  NA 21.45
## 5 2873212765 5/12/2016 11:59:59 PM     57.3     126.3249  NA 21.69
## 6 4319703577 4/17/2016 11:59:59 PM     72.4     159.6147  25 27.45
##   IsManualReport        LogId
## 1           True 1.462234e+12
## 2           True 1.462320e+12
## 3          False 1.460510e+12
## 4           True 1.461283e+12
## 5           True 1.463098e+12
## 6           True 1.460938e+12</code></pre>
<p>We can observe that there are missing values in the weight data,
particularly in the “fat” column.</p>
</div>
<div id="process" class="section level3">
<h3><strong>Process</strong></h3>
<p>Data Cleaning</p>
<pre class="r"><code># Converting column names and fixing date formats

# activity
activity_cleaned &lt;- activity_data %&gt;%
  rename_with(tolower) %&gt;%
  mutate(date = as.Date(activitydate, &quot;%m/%d/%y&quot;)) # fixing date formats

# intensities
intensities_cleaned &lt;- intensities_data %&gt;%
  rename_with(tolower) %&gt;%
  mutate(date = as.Date(activityday, &quot;%m/%d/%y&quot;)) # fixing date formats

# calories
calories_cleaned &lt;- calories_data %&gt;%
  rename_with(tolower) %&gt;%
  rename(activitydate = activityday) %&gt;%
  mutate(date = as.Date(activitydate, &quot;%m/%d/%y&quot;)) # fixing date formats

# steps
steps_cleaned &lt;- steps_data %&gt;%
  rename_with(tolower) %&gt;%
  rename(activitydate = activityday) %&gt;%
  mutate(date = as.Date(activitydate, &quot;%m/%d/%y&quot;)) # fixing date formats

# sleep
sleep_cleaned &lt;- sleep_data %&gt;%
  rename_with(tolower) %&gt;%
  rename(activitydate = sleepday) %&gt;%
  mutate(date = as.Date(activitydate, &quot;%m/%d/%y&quot;)) # fixing date formats

# weight
weight_cleaned &lt;- weight_data %&gt;%
  rename_with(tolower) %&gt;%
  rename(activitydate = date) %&gt;%
  mutate(date = as.Date(activitydate, &quot;%m/%d/%y&quot;)) # fixing date formats</code></pre>
<p>Exploring the data</p>
<pre class="r"><code># Exploring the data
n_distinct(activity_data$Id)</code></pre>
<pre><code>## [1] 33</code></pre>
<pre class="r"><code>n_distinct(intensities_data$Id)</code></pre>
<pre><code>## [1] 33</code></pre>
<pre class="r"><code>n_distinct(calories_data$Id)</code></pre>
<pre><code>## [1] 33</code></pre>
<pre class="r"><code>n_distinct(steps_data$Id)</code></pre>
<pre><code>## [1] 33</code></pre>
<pre class="r"><code>n_distinct(sleep_data$Id)</code></pre>
<pre><code>## [1] 24</code></pre>
<pre class="r"><code>n_distinct(weight_data$Id)</code></pre>
<pre><code>## [1] 8</code></pre>
<p>From the above information, we can identify that there are only 8
data samples from weight data, which cannot be sufficient to deduce some
insights using this data.</p>
</div>
<div id="analyze" class="section level3">
<h3><strong>Analyze</strong></h3>
<p>Let’s identify some statistical insights about the data</p>
<pre class="r"><code>summary(activity_cleaned)</code></pre>
<pre><code>##        id            activitydate         totalsteps    totaldistance   
##  Min.   :1.504e+09   Length:940         Min.   :    0   Min.   : 0.000  
##  1st Qu.:2.320e+09   Class :character   1st Qu.: 3790   1st Qu.: 2.620  
##  Median :4.445e+09   Mode  :character   Median : 7406   Median : 5.245  
##  Mean   :4.855e+09                      Mean   : 7638   Mean   : 5.490  
##  3rd Qu.:6.962e+09                      3rd Qu.:10727   3rd Qu.: 7.713  
##  Max.   :8.878e+09                      Max.   :36019   Max.   :28.030  
##  trackerdistance  loggedactivitiesdistance veryactivedistance
##  Min.   : 0.000   Min.   :0.0000           Min.   : 0.000    
##  1st Qu.: 2.620   1st Qu.:0.0000           1st Qu.: 0.000    
##  Median : 5.245   Median :0.0000           Median : 0.210    
##  Mean   : 5.475   Mean   :0.1082           Mean   : 1.503    
##  3rd Qu.: 7.710   3rd Qu.:0.0000           3rd Qu.: 2.053    
##  Max.   :28.030   Max.   :4.9421           Max.   :21.920    
##  moderatelyactivedistance lightactivedistance sedentaryactivedistance
##  Min.   :0.0000           Min.   : 0.000      Min.   :0.000000       
##  1st Qu.:0.0000           1st Qu.: 1.945      1st Qu.:0.000000       
##  Median :0.2400           Median : 3.365      Median :0.000000       
##  Mean   :0.5675           Mean   : 3.341      Mean   :0.001606       
##  3rd Qu.:0.8000           3rd Qu.: 4.782      3rd Qu.:0.000000       
##  Max.   :6.4800           Max.   :10.710      Max.   :0.110000       
##  veryactiveminutes fairlyactiveminutes lightlyactiveminutes sedentaryminutes
##  Min.   :  0.00    Min.   :  0.00      Min.   :  0.0        Min.   :   0.0  
##  1st Qu.:  0.00    1st Qu.:  0.00      1st Qu.:127.0        1st Qu.: 729.8  
##  Median :  4.00    Median :  6.00      Median :199.0        Median :1057.5  
##  Mean   : 21.16    Mean   : 13.56      Mean   :192.8        Mean   : 991.2  
##  3rd Qu.: 32.00    3rd Qu.: 19.00      3rd Qu.:264.0        3rd Qu.:1229.5  
##  Max.   :210.00    Max.   :143.00      Max.   :518.0        Max.   :1440.0  
##     calories         date           
##  Min.   :   0   Min.   :2020-04-12  
##  1st Qu.:1828   1st Qu.:2020-04-19  
##  Median :2134   Median :2020-04-26  
##  Mean   :2304   Mean   :2020-04-26  
##  3rd Qu.:2793   3rd Qu.:2020-05-04  
##  Max.   :4900   Max.   :2020-05-12</code></pre>
<pre class="r"><code>summary(intensities_cleaned)</code></pre>
<pre><code>##        id            activityday        sedentaryminutes lightlyactiveminutes
##  Min.   :1.504e+09   Length:940         Min.   :   0.0   Min.   :  0.0       
##  1st Qu.:2.320e+09   Class :character   1st Qu.: 729.8   1st Qu.:127.0       
##  Median :4.445e+09   Mode  :character   Median :1057.5   Median :199.0       
##  Mean   :4.855e+09                      Mean   : 991.2   Mean   :192.8       
##  3rd Qu.:6.962e+09                      3rd Qu.:1229.5   3rd Qu.:264.0       
##  Max.   :8.878e+09                      Max.   :1440.0   Max.   :518.0       
##  fairlyactiveminutes veryactiveminutes sedentaryactivedistance
##  Min.   :  0.00      Min.   :  0.00    Min.   :0.000000       
##  1st Qu.:  0.00      1st Qu.:  0.00    1st Qu.:0.000000       
##  Median :  6.00      Median :  4.00    Median :0.000000       
##  Mean   : 13.56      Mean   : 21.16    Mean   :0.001606       
##  3rd Qu.: 19.00      3rd Qu.: 32.00    3rd Qu.:0.000000       
##  Max.   :143.00      Max.   :210.00    Max.   :0.110000       
##  lightactivedistance moderatelyactivedistance veryactivedistance
##  Min.   : 0.000      Min.   :0.0000           Min.   : 0.000    
##  1st Qu.: 1.945      1st Qu.:0.0000           1st Qu.: 0.000    
##  Median : 3.365      Median :0.2400           Median : 0.210    
##  Mean   : 3.341      Mean   :0.5675           Mean   : 1.503    
##  3rd Qu.: 4.782      3rd Qu.:0.8000           3rd Qu.: 2.053    
##  Max.   :10.710      Max.   :6.4800           Max.   :21.920    
##       date           
##  Min.   :2020-04-12  
##  1st Qu.:2020-04-19  
##  Median :2020-04-26  
##  Mean   :2020-04-26  
##  3rd Qu.:2020-05-04  
##  Max.   :2020-05-12</code></pre>
<pre class="r"><code>summary(calories_cleaned)</code></pre>
<pre><code>##        id            activitydate          calories         date           
##  Min.   :1.504e+09   Length:940         Min.   :   0   Min.   :2020-04-12  
##  1st Qu.:2.320e+09   Class :character   1st Qu.:1828   1st Qu.:2020-04-19  
##  Median :4.445e+09   Mode  :character   Median :2134   Median :2020-04-26  
##  Mean   :4.855e+09                      Mean   :2304   Mean   :2020-04-26  
##  3rd Qu.:6.962e+09                      3rd Qu.:2793   3rd Qu.:2020-05-04  
##  Max.   :8.878e+09                      Max.   :4900   Max.   :2020-05-12</code></pre>
<pre class="r"><code>summary(steps_cleaned)</code></pre>
<pre><code>##        id            activitydate         steptotal          date           
##  Min.   :1.504e+09   Length:940         Min.   :    0   Min.   :2020-04-12  
##  1st Qu.:2.320e+09   Class :character   1st Qu.: 3790   1st Qu.:2020-04-19  
##  Median :4.445e+09   Mode  :character   Median : 7406   Median :2020-04-26  
##  Mean   :4.855e+09                      Mean   : 7638   Mean   :2020-04-26  
##  3rd Qu.:6.962e+09                      3rd Qu.:10727   3rd Qu.:2020-05-04  
##  Max.   :8.878e+09                      Max.   :36019   Max.   :2020-05-12</code></pre>
<pre class="r"><code>summary(sleep_cleaned)</code></pre>
<pre><code>##        id            activitydate       totalsleeprecords totalminutesasleep
##  Min.   :1.504e+09   Length:413         Min.   :1.000     Min.   : 58.0     
##  1st Qu.:3.977e+09   Class :character   1st Qu.:1.000     1st Qu.:361.0     
##  Median :4.703e+09   Mode  :character   Median :1.000     Median :433.0     
##  Mean   :5.001e+09                      Mean   :1.119     Mean   :419.5     
##  3rd Qu.:6.962e+09                      3rd Qu.:1.000     3rd Qu.:490.0     
##  Max.   :8.792e+09                      Max.   :3.000     Max.   :796.0     
##  totaltimeinbed       date           
##  Min.   : 61.0   Min.   :2020-04-12  
##  1st Qu.:403.0   1st Qu.:2020-04-19  
##  Median :463.0   Median :2020-04-27  
##  Mean   :458.6   Mean   :2020-04-26  
##  3rd Qu.:526.0   3rd Qu.:2020-05-04  
##  Max.   :961.0   Max.   :2020-05-12</code></pre>
<pre class="r"><code>summary(weight_cleaned)</code></pre>
<pre><code>##        id            activitydate          weightkg       weightpounds  
##  Min.   :1.504e+09   Length:67          Min.   : 52.60   Min.   :116.0  
##  1st Qu.:6.962e+09   Class :character   1st Qu.: 61.40   1st Qu.:135.4  
##  Median :6.962e+09   Mode  :character   Median : 62.50   Median :137.8  
##  Mean   :7.009e+09                      Mean   : 72.04   Mean   :158.8  
##  3rd Qu.:8.878e+09                      3rd Qu.: 85.05   3rd Qu.:187.5  
##  Max.   :8.878e+09                      Max.   :133.50   Max.   :294.3  
##                                                                         
##       fat             bmi        ismanualreport         logid          
##  Min.   :22.00   Min.   :21.45   Length:67          Min.   :1.460e+12  
##  1st Qu.:22.75   1st Qu.:23.96   Class :character   1st Qu.:1.461e+12  
##  Median :23.50   Median :24.39   Mode  :character   Median :1.462e+12  
##  Mean   :23.50   Mean   :25.19                      Mean   :1.462e+12  
##  3rd Qu.:24.25   3rd Qu.:25.56                      3rd Qu.:1.462e+12  
##  Max.   :25.00   Max.   :47.54                      Max.   :1.463e+12  
##  NA&#39;s   :65                                                            
##       date           
##  Min.   :2020-04-12  
##  1st Qu.:2020-04-19  
##  Median :2020-04-27  
##  Mean   :2020-04-26  
##  3rd Qu.:2020-05-04  
##  Max.   :2020-05-12  
## </code></pre>
<div id="identified-trends" class="section level4">
<h4><strong>Identified Trends</strong></h4>
<ul>
<li><p>Activity Summary: Average steps: 7638 (below CDC’s 10000
recommendation) Average sedentary minutes: 991.2 (16.52 hours),
suggesting a need for reduction.</p></li>
<li><p>Intensities Summary: Average lightly active minutes: 199,
indicating predominant light activity.</p></li>
<li><p>Calories Summary: Average BMI: 25.19 (overweight; caution without
age and gender context)</p></li>
<li><p>Steps Summary: Average daily steps: 7638.</p></li>
<li><p>Sleep Summary: Average sleep duration: 419.5 minutes. Average
total time in bed: 458.6 minutes.</p></li>
<li><p>Weight Summary: Average BMI: 25.19 (overweight; caution without
age and gender context).</p></li>
</ul>
</div>
</div>
<div id="share" class="section level3">
<h3><strong>Share</strong></h3>
<p>Let’s assume few hypothesis and create visualizations to validate
them.</p>
<pre class="r"><code># The total steps taken are positively correlated with calories burned
ggplot(data = activity_cleaned, mapping = aes(x = totalsteps, y = calories, color = date)) + 
  geom_point() + geom_smooth() +
  labs(title = &quot;Total Steps vs. Calories&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula = &#39;y ~ x&#39;</code></pre>
<p><img
src="Bellabeat_Case_Study_files/figure-html/unnamed-chunk-6-1.png" /><!-- --></p>
<p>There is an actual positive correlation between the total steps and
calories burned.</p>
<pre class="r"><code># The total sleep duration has a negative correlation with calories burned
merged1 &lt;- merge(sleep_cleaned, calories_cleaned, by = c(&#39;id&#39;, &#39;date&#39;))
ggplot(data = merged1, mapping = aes(x = totalminutesasleep, y = calories, color = date)) +
  geom_point() + geom_smooth() +
  labs(title = &quot;Total Sleep Minutes vs. Calories&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula = &#39;y ~ x&#39;</code></pre>
<p><img
src="Bellabeat_Case_Study_files/figure-html/unnamed-chunk-7-1.png" /><!-- --></p>
<p>There is neither positive nor negative correlation between the total
sleep minutes and calories burned. That means, Sleeping more has no
direct effect on buring more calories.</p>
<pre class="r"><code># Sedentary minutes have a positive correlation with BMI
merged3 &lt;- merge(weight_cleaned, activity_cleaned, by = c(&#39;id&#39;, &#39;date&#39;))
ggplot(data = merged3, mapping = aes(y = bmi, x = sedentaryminutes, color = date)) +
  geom_point() + geom_smooth() +
  labs(title = &quot;Sedentary Minutes vs. BMI&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula = &#39;y ~ x&#39;</code></pre>
<p><img
src="Bellabeat_Case_Study_files/figure-html/unnamed-chunk-8-1.png" /><!-- --></p>
<p>There is a positive correlation between the Sedentary Minutes and
BMI. It means that people with higher BMI (usually overweight people
based on their age/gender) usually have high sedentary minutes.
Therefore, it is highly important to reduce the sedentary minutes and
maintain good activity.</p>
<pre class="r"><code># Total time asleep has a positive correlation with total time in bed
ggplot(data = sleep_cleaned, mapping = aes(x = totaltimeinbed, y = totalminutesasleep, color = date)) + 
  geom_point() + geom_smooth() +
  labs(title = &quot;Total Time Asleep vs. Total Time in Bed&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula = &#39;y ~ x&#39;</code></pre>
<p><img
src="Bellabeat_Case_Study_files/figure-html/unnamed-chunk-9-1.png" /><!-- --></p>
<p>This suggests that there is a positive correlation between time
asleep and total time in bed. That clearly means, the more time people
spend in their bed, the more time they are asleep.</p>
<pre class="r"><code># The total sedentary minutes have a negative correlation with total calories burned
merged2 &lt;- merge(intensities_cleaned, calories_cleaned, by = c(&#39;id&#39;, &#39;date&#39;))
ggplot(data = merged2, mapping = aes(x = sedentaryminutes, y = calories, color = date)) +
  geom_point() + geom_smooth() +
  labs(title = &quot;Total Sedentary Minutes vs. Calories&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula = &#39;y ~ x&#39;</code></pre>
<p><img
src="Bellabeat_Case_Study_files/figure-html/unnamed-chunk-10-1.png" /><!-- --></p>
<p>This suggests a negative correlation between the total calories
burned vs total sedentary minutes spent. This means that if a person
spent more time with no activity, then they burned less calories.</p>
</div>
<div id="phase" class="section level3">
<h3><strong>Phase</strong></h3>
<p><strong>Final Conclusion:</strong></p>
<ul>
<li>Propose an overhaul of the app’s features based on user preferences
and engagement levels.</li>
<li>Emphasize the need for addressing insomnia, sedentary behavior, and
obesity in users.</li>
</ul>
<p><strong>Application of Insights:</strong></p>
<ul>
<li>Implement suggested changes in the Bellabeat app, including feature
improvements and additions.</li>
<li>Introduce targeted marketing strategies focusing on health
improvement and community building.</li>
</ul>
<p><strong>Next Steps:</strong></p>
<ul>
<li>Initiate a phased rollout of app updates with enhanced
features.</li>
<li>Monitor user feedback and engagement post-update for continuous
improvement.</li>
<li>Evaluate the effectiveness of marketing campaigns through user
engagement metrics.</li>
</ul>
<p><strong>Additional Data Consideration:</strong></p>
<ul>
<li>Collect user feedback on new features and iterate accordingly.</li>
<li>Explore user demographics and preferences to tailor app features
more effectively.</li>
</ul>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
